# Generated by Django 5.2.3 on 2025-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название статьи",
                        max_length=300,
                        unique=True,
                        verbose_name="Название статьи",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Введите имя автора",
                        max_length=100,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите текст статьи", verbose_name="Содержание"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для статьи",
                        null=True,
                        upload_to="blog/photos",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания статьи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления статьи"
                    ),
                ),
                ("publication_status", models.BooleanField(default=False)),
                ("number_of_views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["title"],
            },
        ),
    ]
