# Generated by Django 5.2.3 on 2025-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="number_of_views",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
