# Generated by Django 5.2.4 on 2025-08-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_number_of_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["title"],
                "permissions": [
                    ("can_publish_article", "Может публиковать статьи"),
                    ("can_change_any_article", "Может изменять любые статьи"),
                    ("can_delete_any_article", "Может удалять любые статьи"),
                ],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
