# Generated by Django 5.2.4 on 2025-08-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликовано"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                help_text="Выберите статус публикации продукта",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
